# Generated by Django 5.0.6 on 2024-07-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0002_rename_mobilenet_model_cnn_model_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="unet_model",
            fields=[
                ("User_id", models.AutoField(primary_key=True, serialize=False)),
                ("model_accuracy", models.CharField(max_length=10)),
                ("executed", models.CharField(max_length=10, null=True)),
            ],
            options={
                "db_table": "unet",
            },
        ),
    ]
