# Generated by Django 5.0.6 on 2024-07-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0003_unet_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="comparison_graph",
            name="unet",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
