# Generated by Django 3.2 on 2025-03-03 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_comparison_graph_unet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='unet_model',
            new_name='unetplusplus_model',
        ),
        migrations.RenameField(
            model_name='comparison_graph',
            old_name='unet',
            new_name='unetplusplus',
        ),
    ]
